//= require "core/monocle"
//= require "compat/env"
//= require "compat/css"
//= require "compat/stubs"
//= require "compat/browser"
//= require "core/factory"
//= require "core/events"
//= require "core/styles"
//= require "core/reader"
//= require "core/book"
//= require "core/place"
//= require "core/component"
//= require "controls/panel"
//= require "panels/twopane"
//= require "panels/imode"
//= require "panels/eink"
//= require "panels/marginal"
//= require "dimensions/vert"
//= require "flippers/legacy"
//= require "dimensions/columns"
//= require "flippers/slider"
//= require "flippers/scroller"
//= require "flippers/instant"

Monocle.pieceLoaded('monocore');
